### ISSUE TITLE
Convert Epic Save to Steam Save

### ISSUE THREAD

**Issue by getbiks** [Green-Bat/Savefile-Converter#1]
I am trying to save my Epic Arkham City save to Steam save. Is it possible? Will be very very helpful

**Comment by Green-Bat** [comment]
It is possible to convert from Epic to Steam, however this program was made specifically for Steam to Epic, adding the functionality for it to do the opposite would mean the automatic game detection feature would no longer be possible, which is something I would rather keep. If you want to just convert a couple files for yourself you can use a hex editor and just remove the first 4 bytes of the Epic save.

**Comment by Green-Bat** [comment]
Two way conversion is now a feature
