### ISSUE TITLE
Switch Support

### ISSUE THREAD

**Issue by gustavoab2** [Green-Bat/Savefile-Converter#3]
I am writing to express my enjoyment of playing 'Arkham Asylum' on my Nintendo Switch. While the overall experience has been excellent, I've noticed that the performance on the Switch is somewhat average. I believe adding support for save file conversion from the Nintendo Switch version to the Steam or Epic Games versions could significantly enhance the player experience.

Would it be possible to consider implementing a feature that allows players to transfer their save files from the Nintendo Switch to the Steam or Epic Games platforms? I have attached my 'Arkham Asylum' save file. This might help you.
[SaveData.zip](https://github.com/Green-Bat/Savefile-Converter/files/13622794/SaveData.zip)

**Comment by gustavoab2** [comment]
sorry for this im new to github

**Comment by ShikenNuggets** [comment]
Modifying the save data to work between different platforms is way more difficult and complicated than doing it for the different PC versions (I actually don't even know how to do it for Switch, but if it's anything like the other consoles then it's a nightmare) and, IMO, well beyond the scope of this utility.

**Comment by Green-Bat** [comment]
Like Shiken said cross-platform conversion is typically much more trouble than it's worth, there's very little info pertaining to conversion to-and-from Switch, specifically for these games, so for the time being I won't be implementing this.
